name: Hexo Deploy
concurrency:
  group: "pages"
  cancel-in-progress: true
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取完整源码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 配置Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: 安装项目依赖
        run: npm install
      - name: Hexo 构建静态文件
        run: npx hexo clean && npx hexo generate
      - name: 部署到 gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
